#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# apo_data:
#     path: /api/data
#     # the controller value has the format 'controller_class::method_name'
#     controller: App\Controller\DataController::data

oauth2:
    resource: '@TrikoderOAuth2Bundle/Resources/config/routes.xml'
    
api_login_check:
    path: /api/login_check