# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration


services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Apifarm\CoreBundle\:
        public: true
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../Kernel.php'
            - '../../Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Apifarm\CoreBundle\Controller\:
        resource: '../../Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    MongoDB\Client:
        public: true
        autowire: true
        arguments: [ '%apifarm.db%' ]
    
    Apifarm\CoreBundle\Services\ICrudService: '@Apifarm\CoreBundle\Services\CrudService'

    Apifarm\CoreBundle\EventListener\UserResolveListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: trikoder.oauth2.user_resolve, method: onUserResolve }



    Apifarm\CoreBundle\Entity\Fields\IntFieldType:
        tags: ['app.fieldtype']

    Apifarm\CoreBundle\Entity\Fields\TextFieldType:
        tags: ['app.fieldtype']

    Apifarm\CoreBundle\Services\TypeService:
        arguments:
            - !tagged app.fieldtype

    Apifarm\CoreBundle\EventListener\DataChanged\:
         resource: '../../EventListener/DataChanged/'
         tags:
            - { name: kernel.event_listener, event: app.crud.datachanged, method: onPreSave }